on: [push]

jobs:
  deploy_thor:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: ./.github/actions/deploy_thor
        with:
          opco: 'Alh'
