on: [push]

jobs:
  alh_nonprd:
    runs-on: ubuntu-latest
    name: ALH nonprd
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: ./.github/actions/deploy_thor
        with:
          opco: 'Alh'
  
  alh_prd:
    runs-on: ubuntu-latest
    needs: alh_nonprd
    name: ALH prd
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: ./.github/actions/deploy_thor
        with:
          opco: 'Alh_prd'
