name: Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

concurrency:
  group: deploy
  cancel-in-progress: false

jobs:
  alh:
    uses: ./.github/workflows/template.yml
    with:
      opco: "alh"

