name: Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

concurrency:
  group: deploy
  cancel-in-progress: false

jobs:
  ALH:
    uses: ./.github/workflows/template.yml
    with:
      opco: "alh"
      deploy_prd: true
  GGA:
    uses: ./.github/workflows/template.yml
    with:
      opco: "alh"
      deploy_prd: true
  ETS:
    uses: ./.github/workflows/template.yml
    with:
      opco: "ets"
      deploy_prd: true
  GSO:
    uses: ./.github/workflows/template.yml
    with:
      opco: "gso"
      deploy_prd: false
  

